#!/bin/bash
### BEGIN INIT INFO
# Provides:          hydroxide-smtp
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: hydroxide smtp relay
# Description:       start stop restart status
### END INIT INFO

# Using the lsb functions to perform the operations.
. /lib/lsb/init-functions

# change your hydroxide bin PATH here
DAEMON=/root/gowork/bin/hydroxide

NAME=hydroxide
PIDFILE=/var/run/$NAME-smtp.pid
LOGFILE=/var/log/$NAME
STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"

test -x $DAEMON || exit 0

if [ -z "$DAEMONOPTS" ]; then
    DAEMONOPTS="smtp"
fi

start() {
    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
        --background --oknodo --startas /bin/bash -- -c "exec $DAEMON $DAEMONOPTS > $LOGFILE 2>&1"
}

stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry=$STOP_SCHEDULE \
        --name $NAME --oknodo
    rm -f $PIDFILE
}

status() {
    if [ -f $PIDFILE ]; then
        if kill -0 $(cat "$PIDFILE"); then
			log_success_msg "is running"
        else
			log_failure_msg "is dead, but pidfile exists"
        fi
    else
		log_warning_msg "is not running"
    fi
}

case "$1" in
    start)
		log_daemon_msg "Starting the process" "$NAME"
        start
    ;;
    stop)
		log_daemon_msg "Stopping the process" "$NAME"
        stop
    ;;
    restart)
        echo "Restarting $NAME"
        stop
        start
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 2
    ;;
esac

exit 0
